document.addEventListener('DOMContentLoaded',()=>{
const $=id=>document.getElementById(id);let currentRack=null;let sortKey=null,sortAsc=true;
function clock(){const n=new Date();$('clock').textContent='HORA ACTUAL: '+n.toLocaleTimeString('es-AR',{hour12:false});}$('lastPing').textContent='ÚLTIMO PING: --:--:--';clock();setInterval(clock,1000);
const views=[$('home'),$('devicesView'),$('racksView')];function show(v){views.forEach(x=>x.classList.add('hidden'));v.classList.remove('hidden')}
function stats(){ $('totalIPs').textContent=devices.length;$('onlineIPs').textContent=devices.filter(d=>d.status==='online').length;$('offlineIPs').textContent=devices.filter(d=>d.status==='offline').length }
function groups(){const c=$('groups');c.innerHTML='';GROUPS.forEach(g=>{const n=devices.filter(d=>d.group===g).length;const b=document.createElement('button');b.className='groupCard';b.innerHTML=`<h3>${g}</h3><p>${n} dispositivo${n===1?'':'s'}</p>`;b.onclick=()=>renderDevices(g);c.appendChild(b)})}
function renderDevices(group,onlyProblems=false){show($('devicesView'));$('devicesTitle').textContent=onlyProblems?'SOLO PROBLEMAS':group;let a=devices.filter(d=>(!group||d.group===group)&&(!onlyProblems||d.status==='offline'));if(sortKey)a.sort((x,y)=>String(x[sortKey]||'').localeCompare(String(y[sortKey]||''),undefined,{numeric:true})*(sortAsc?1:-1));const body=$('devicesBody');body.innerHTML='';a.forEach(d=>{const tr=document.createElement('tr');tr.innerHTML=`<td><button class="iplink" style="border:0;background:none;color:#1261a0;cursor:pointer">${d.ip||''}</button></td><td>${d.hostname||''}</td><td></td><td>${d.connection||'—'}</td><td>${d.status==='online'?'ONLINE':'OFFLINE'}</td>`;const sel=document.createElement('select');SECTORES.forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;o.selected=s===d.location;sel.appendChild(o)});sel.onchange=()=>d.location=sel.value;tr.children[2].appendChild(sel);tr.querySelector('.iplink').onclick=()=>alert(`IP: ${d.ip}\nHOSTNAME: ${d.hostname||'—'}\nUBICACIÓN: ${d.location||'—'}\nGRUPO: ${d.group||'—'}\nRACK: ${d.rack||'—'}\nSECTOR: ${d.sector||'—'}\nSW: ${d.sw||'—'}\nBOCA: ${d.boca||'—'}\nMARCA: ${d.marca||'—'}\nDESCRIPCIÓN: ${d.descripcion||'—'}`);body.appendChild(tr)})}
function racks(){const c=$('rackButtons');c.innerHTML='';RACKS.forEach(([r,s])=>{const b=document.createElement('button');b.className='rackButton';b.innerHTML=`<span class="rackNumber">${r}</span><span class="rackSector">${s}</span>`;b.onclick=()=>openRack(r,s);c.appendChild(b)})}
function openRack(r,s){currentRack=r;$('rackPicker').classList.add('hidden');$('rackContent').classList.remove('hidden');$('rackTitle').textContent=`RACK ${r} - ${s}`;renderRack()}
function renderRack(){const q=$('rackFilter').value.toLowerCase();const body=$('rackBody');body.innerHTML='';(rackData[currentRack]||[]).filter(row=>Object.values(row).join(' ').toLowerCase().includes(q)).forEach((row,i)=>{const tr=document.createElement('tr');['rack','sector','patch','sw','boca','marca','descripcion','hostname','ip'].forEach(k=>{const td=document.createElement('td');const inp=document.createElement('input');inp.value=row[k]||'';inp.oninput=()=>row[k]=inp.value;td.appendChild(inp);tr.appendChild(td)});body.appendChild(tr)})}
$('racksBtn').onclick=()=>{show($('racksView'));$('rackPicker').classList.remove('hidden');$('rackContent').classList.add('hidden');racks()};$('backRacks').onclick=()=>{if(!$('rackContent').classList.contains('hidden')){$('rackContent').classList.add('hidden');$('rackPicker').classList.remove('hidden')}else show($('home'))};$('backDevices').onclick=()=>show($('home'));$('problemsBtn').onclick=()=>renderDevices(null,true);$('rfidBtn').onclick=()=>alert('RFID: módulo pendiente de integración.');$('rackFilter').oninput=renderRack;$('addRackRow').onclick=()=>{const [r,s]=RACKS.find(x=>x[0]===currentRack)||[currentRack,''];rackData[currentRack].push({rack:r,sector:s,patch:'',sw:'',boca:'',marca:'',descripcion:'',hostname:'',ip:''});renderRack()};$('photoBtn').onclick=()=>alert(`Foto del ${$('rackTitle').textContent}: módulo de fotos pendiente de incorporar.`);
document.querySelectorAll('th[data-sort]').forEach(th=>th.onclick=()=>{const k=th.dataset.sort;if(sortKey===k)sortAsc=!sortAsc;else{sortKey=k;sortAsc=true}renderDevices(null,false)});
groups();stats();
});